### ISSUE TITLE
`pointer-events` style not removed after cancel.

### ISSUE THREAD

**Issue by taheilo** [rwwagner90/ember-shepherd#22] opened 2015-11-06 08:50 UTC
`pointer-events` doesn't get removed from last step when exit button is pressed, which disables the button.

**Comment by taheilo** [comment] 2015-11-06 11:21
Also keeps the ember-shepherd specific classes on the element.

**Comment by rwwagner90** [comment] 2015-11-09 18:34
@taheilo I'm not quite following what the issue is here. The classes do stay on the element. This is the behavior built into Shepherd, so that we don't have to loop through and apply all the classes every time the tour is started.

If you can elaborate and/or provide some sample code or jsbin or similar, I will be glad to look into this.

**Comment by rwwagner90** [comment] 2016-01-04 18:31
@taheilo could you please help us out with an example or some elaboration here?

**Comment by craigsketchley** [comment] 2016-01-25 12:27
Hey @rwwagner90. Cheers for making this library. I'm having the same issue as @taheilo.

Basically the attribute `style="pointer-events: none;"` is left on any `shepherd-element` after shepherd completes or cancels. So if I have some buttons that are the target elements in one of the shepherd steps, they are un-clickable after a shepherd tour finishes.

To fix this, I'm currently doing the following on tour complete or cancel:

```
var done = function() {
  // Clean up shepard targets
  _.map(document.getElementsByClassName('shepherd-target'), function(elem) {
    elem.style.pointerEvents = '';
  });
};
tour.on('cancel', done);
tour.on('complete', done);
```

**Comment by rwwagner90** [comment] 2016-01-25 15:20
Hi @craigsketchley seems like something I should be able to fix pretty easily. Are you using the 2.0.0 version of ember-shepherd? How are you liking the library?

**Comment by craigsketchley** [comment] 2016-01-26 01:14
Yep, I'm using v2.0.0. The library has been a great help integrating Shepherd into my Ember app, cheers. I'm pretty new to Ember so have trouble finding the best way to integrate external libraries. I wouldn't mind contributing if you've got anything that needs doing?

**Comment by rwwagner90** [comment] 2016-01-26 14:05
@craigsketchley glad it has helped you out! If you would like to contribute, we would love to have you. When the tour completes or cancels, the cleanup method gets called, and it is supposed to set the pointerEvents back to `'auto'`, but it appears it is only doing so for the currentStep and not all the elements. If you would like to take a stab at fixing the cleanup method and writing a test that shows the pointer-events are set to `'none'` initially, and set back to `'auto'` after cancel or complete, that would be awesome :smile:

**Comment by craigsketchley** [comment] 2016-01-27 00:24
Yeah, great. Happy to help out with that issue and cheers for the guidance. I'll let you know how I go.

**Comment by maxkwallace** [comment] 2016-01-29 11:29
Just want to confirm that I'm running into the same issue as @taheilo and @craigsketchley. A fix for this would be awesome!

**Comment by rwwagner90** [comment] 2016-01-29 15:01
@craigsketchley are you working on a fix? If not, I'd be happy to work on a fix this weekend

**Comment by craigsketchley** [comment] 2016-01-29 21:28
Yeah, sorry it took me a while to get round to it. How's this? #33

**Comment by rwwagner90** [comment] 2016-01-30 01:44
@craigsketchley no worries. PR looked great, I went ahead and merged. Thanks a bunch! Are you interested in being added as a contributor to the repo and helping with various things? Any other ideas for improvements or features?

**Comment by rwwagner90** [comment] 2016-01-30 14:51
@taheilo @maxkwallace @craigsketchley I have merged the work that @craigsketchley did and I published the new version 2.0.1. Please grab the new version and let me know if the problem is fixed!

**Comment by maxkwallace** [comment] 2016-01-30 16:21
Just updated to `2.0.1`. Looks good to me-- thanks for the fix, and the addon!

**Comment by rwwagner90** [comment] 2016-01-30 16:23
Glad it works for you @maxkwallace! Feel free to throw some stars our way if you want :wink:

**Closed** 2016-01-30 16:23 UTC

**Comment by craigsketchley** [comment] 2016-01-31 04:24
Thanks @rwwagner90. Yes, I'd love to help out with a few more things. I'll have to have a think about some new features/improvements.

I'm currently trying to implement a tour on a responsive site, so I need to have some different tour steps depending on device, any thoughts on the best practice for this? One other thing I noticed was the tour would persist if you navigated to another route (e.g. using the browser back button), what's the expected behaviour for this? Is it the developers responsibility to clean up any tour on transition? I'll be playing with `ember-shepherd` a bit more over the coming days so I'll let you know if I think of anything else.

**Comment by rwwagner90** [comment] 2016-01-31 13:50
@craigsketchley do you use gitter? Might be easier to chat there than in these issues. 

I haven't thought about switching steps out based on device. We would have to do some device detection and then maybe set flags on each step for what devices it should be displayed on or something. I'm open to suggestions, but it does not sound like an easy problem to solve. It might be easier to just create completely separate tours and enable the different steps based on device on your end rather than adding it to the library. We'll have to discuss this further.

Regarding route change, I think we decided this was the intention because you could have a tour that spanned multiple routes perhaps. I'd be open to making this configurable. Maybe set a flag on the tour `destroyOnRouteChange` or something.

Definitely let me know what ideas you have. You have been added to package.json and bower.json and you are a collaborator in GitHub now. Feel free to implement any ideas and submit PRs :smile: . 

If you use gitter, just jump in our room and tag me anytime you need my attention, or I am also on the Ember slack as rwwagner90 there as well.
